spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 1234
    url: jdbc:postgresql://localhost:5433/jolybell
    username: postgres
    hikari:
      minimum-idle: 1
      max-lifetime: 40000
      keepalive-time: 30000

  jpa:
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  sql:
    init:
      encoding: UTF-8
  devtools:
    livereload:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: jolybellacer@gmail.com
    password: cojuqcfexndfhnjn
    url: http://localhost:8080/auth/verify
    #    password: jolybellAcer1!
    defaultEncoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    uz:
      greenstar:
        DEBUG

jwt:
  secret:
    key: secretkey

image:
  source:
    base-url: D:/Institut/Diplom ishi/Angular/All/JolyBell/src/

paysys:
  url: https://paysys.uz/gateway
  serviceId: paySysServiceId
  secretKey: paySysSecretKey
  vendorId: paySysVendorId

